POST http://localhost:3004/api/notes
Content-Type: application/json

{
    "content": "lolllllll"
}

###
GET http://localhost:8080/api/notes

###
DELETE http://localhost:8080/api/notes/630e2fd45ec90471cce28125

###
POST https://test-hms.herokuapp.com/api/auth/signin
Content-Type: application/json

{
    "usernameOrEmail": "ibukunod@yahoo.com",
    "password": "1801486cu"
}